### ISSUE TITLE
Feature request: String input for device ID and no default device ID

### ISSUE THREAD

**Issue by keithicus** [OTL/cv_camera#4]
Change device id from int32 to string.  This would allow the user to access IP cameras.

Also, it seems that the default device ID is 0.  I tried launching with a string for the device ID and instead of opening the IP camera that I was trying to connect to, it opened device 0.  This behavoir is not intuitive.  I would expect and error if it failed to open the device I was to connect to.

**Comment by falkoschindler** [comment]
I'd like to request this feature as well.

In order to distinguish multiple cameras I generate symlinks like /dev/logitech to /dev/video0 using /etc/udev/rules.d/. With an integer device id I can't be sure which camera is which device after rebooting. A string would allow to open the Logitech camera explicitly.

**Comment by OTL** [comment]
Hi

It seems possible to use ~file parameter to set device file.
(I have not tested yet, just read the code)

Could you try ~file param?

**Comment by falkoschindler** [comment]
Unfortunately, using the `file` parameter yields an error:
> cv camera open failed: file /dev/usbcam3 cannot be opened.

**Comment by OTL** [comment]
thanks!

below link shows that nobody answers the question "how to open with device file path".

http://stackoverflow.com/questions/20266743/using-device-name-instead-of-id-in-opencv-method-videocapture-open

If you find the answer, please let me know!

**Comment by falkoschindler** [comment]
Yes, I've also seen this post.

Don't you think [one of the two answers](http://stackoverflow.com/a/29081412/3419103) might work in your case? If you follow the symbolic link `/dev/logitech` and get the path of the actual device `/dev/video42`, you might be able to extract the device id 42.

**Comment by OTL** [comment]
I really know what you want, why you want, because I also have experienced exactly same situation for several time.

My concern is 

- Is it portable (at least, it should work on osx, possibly windows...)?
- I don't want to add dependencies like boost::filesystem, if possible.

Isn't it possible to use static video number using udev?

**Comment by falkoschindler** [comment]
I totally understand your concerns.

I'll look into assigning static video numbers using udev, as you suggest. It can take some time, since it's currently not my main focus. I just found cv_camera, liked it for its nodelet functionality, but struggled with the device id and, thus, quickly voted for this feature request. :)

**Comment by seremis** [comment]
Hi,

It seems that the StackOverflow question linked earlier ([here](https://stackoverflow.com/questions/20266743/using-device-name-instead-of-id-in-opencv-method-videocapture-open) has finally been answered, so this would resolve this issue.

**Comment by OTL** [comment]
It seems great.
waiting PR.

2017/09/28 14:35 "Maurice Meedendorp" <notifications@github.com>:

**Comment by seremis** [comment]
I posted a PR on this issue #8

**Comment by OTL** [comment]
Thank you! Added some small comments. Could you fix them?

**Comment by OTL** [comment]
merged
